export const CREATE_AUCTION = 'AUCTION/CREATE_AUCTION';
export const CREATE_AUCTION_SUCCESS = 'AUCTION/CREATE_AUCTION_SUCCESS';
export const GET_AUCTION = 'AUCTION/GET_AUCTION';
export const REQUEST_AUCTION = 'AUCTION/REQUEST_AUCTION';
export const GET_TOTAL_AUCTION = 'AUCTION/GET_TOTAL_AUCTION';
export const REQUEST_TOTAL_AUCTION = 'AUCTION/REQUEST_TOTAL_AUCTION';