export const REGISTRATION = 'AUTH/REGISTRATION';
export const REGISTRATION_SUCCESS = 'AUTH/REGISTRATION_SUCCESS';
export const LOGIN = 'AUTH/LOGIN';
export const LOGIN_SUCCESS = 'AUTH/LOGIN_SUCCESS';
export const LOGOUT = 'AUTH/LOGOUT';
export const LOGIN_GOOGLE = 'AUTH/LOGIN_GOOGLE';
export const CONFIRM_EMAIL = 'AUTH/CONFIRM_EMAIL';
export const REFRESH_PASSWORD = 'AUTH/REFRESH_PASSWORD';