export const REGISTRATION = 'AUTH/REGISTRATION';
export const REGISTRATION_SUCCESS = 'AUTH/REGISTRATION_SUCCESS';
export const LOGIN = 'AUTH/LOGIN';
export const LOGIN_SUCCESS = 'AUTH/LOGIN_SUCCESS';
export const LOGOUT = 'AUTH/LOGOUT';