export const GET_CARDS = 'CARDS/GET_CARDS';
export const REQUEST__CARDS_WITHOUT_PAGINATION = 'CARDS/REQUEST__CARDS_WITHOUT_PAGINATION';
export const REQUEST_CARDS = 'CARDS/REQUEST_CARDS';
export const CREATE_CARD = 'CARDS/CREATE_CARD';
export const CREATE_CARD_SUCCESS = 'CARDS/CREATE_CARD_SUCCESS';