export const GET_CARDS = 'CARDS/GET_CARDS';
export const REQUEST_CARDS = 'CARDS/REQUEST_CARDS';
export const REQUEST_CARDS_WITHOUT_FILTER = 'CARDS/REQUEST_CARDS_WITHOUT_FILTER';
export const CREATE_CARD = 'CARDS/CREATE_CARD';
export const CREATE_CARD_SUCCESS = 'CARDS/CREATE_CARD_SUCCESS';