export const GET_CHATS = 'CHATS/GET_CHATS';
export const REQUEST_CHATS = 'CHATS/REQUEST_CHATS';
export const CREATE_CHAT = 'CHATS/CREATE_CHAT';
export const CREATE_CHAT_SUCCESS = 'CHATS/CREATE_CHAT_SUCCESS';