export const GET_USERS = 'USERS/GET_USERS';
export const REQUEST_USERS = 'USERS/REQUEST_USERS';
export const GET_TOTAL_USERS = 'USERS/GET_TOTAL_USERS';
export const REQUEST_TOTAL_USERS = 'USERS/REQUEST_TOTAL_USERS';