export const GET_USER = 'USER/GET_USER';
export const REQUEST_USER = 'USER/REQUEST_USER';
export const EDIT_USERDATA = 'USER/EDIT_USERDATA';
export const GET_BALANCE = 'USER/GET_BALANCE';
export const REQUEST_BALANCE = 'USER/REQUEST_BALANCE';
export const CHANGE_BALANCE = 'USER/CHANGE_BALANCE';