export const GET_USER = 'USER/GET_USER';
export const REQUEST_USER = 'USER/REQUEST_USER';
export const EDIT_USERDATA = 'USER/EDIT_USERDATA';
export const GET_SOLD_USER_CARDS = 'USER/GET_SOLD_USER_CARDS';
export const REQUEST_SOLD_USER_CARDS = 'USER/REQUEST_SOLD_USER_CARDS';